### ISSUE TITLE
following instructions in the repo doesn't create an index.html file

### ISSUE THREAD

**Issue by raivatshah** [stripe-samples/mobile-saving-card-without-payment#1]
Following instructions in the readme doesn't automatically create an index.html in the client directory.

**Comment by sergei** [comment]
Same here. The instruction on a client page:

> Once you've started the server, open http://localhost:4242 in your browser to check that the server is running locally.

is bit misleading since server returns 500 error:

> jinja2.exceptions.TemplateNotFound: index.html
> 192.168.7.26 - - [18/Feb/2020 20:12:18] "GET / HTTP/1.1" 500 -

Although that doesn't affect the demo functionality.

**Comment by dtp5** [comment]
Still `no such file or directory, stat '/mobile-saving-card-without-payment/client/index.html'`. Any update on this?

**Comment by yuki-stripe** [comment]
Hey all,

Thanks for bringing this up, and sorry for the delay here. I've removed the misleading instructions - like @sergei mentions, there's no need to hit the server on the browser.

**Comment by raivatshah** [comment]
Thanks @yuki-stripe !
